### ISSUE TITLE
Ore e minuti

### ISSUE THREAD

**Issue by KibGim** [italia/writing-toolkit#18]
Nella pagina 
https://docs.italia.it/italia/designers-italia/writing-toolkit/it/bozza/suggerimenti-di-scrittura/numeri-e-date.html
Consiglio di aggiungere **Ore e minuti**.
Ore e minuti non si scrivono separandoli da "." o "," ma da ":"
es: 18:06

(Bella la bozza del glossario, finalmente con esempi pratici. 
idea fuori dalla Issue:
Magari prima che l'AI scriva gli articoli da soli, potreste pensare a un semplice funzione (JS o qualcosa del genere) che es: analizza URL della pagina e evidenzia probabili termini "brurocratesi".
Ovviamente è la conoscenza e la formazione di chi scrive che la fa da padrone).

**Comment by KibGim** [comment]
Che ne pensate della prima parte?

Rispetto alla seconda parte, magari questo controllo sui termini potrebbe essere legato a quanto ho letto su "[Docs Italia, documenti più semplici per una Pubblica Amministrazione più semplice](https://medium.com/team-per-la-trasformazione-digitale/docs-italia-open-government-simpler-documents-public-administration-language-communication-7d1d21b944a4)"
rispetto al punto
> per ciascun ente di creare una sezione dedicata all’interno di Docs Italia
con dei **Warning** _prima_ di procedere alla pubblicazione.

**Comment by pdavide** [comment]
Ciao @KibGim rispetto alla tua prima proposta, mi sembra opportuno inserire un riferimento anche alla formattazione degli orari. Puoi fare un pull request apportando le opportune modifiche al file https://github.com/italia/writing-toolkit/blob/master/suggerimenti-di-scrittura/numeri-e-date.rst.

Rispetto alla seconda proposta:
- i warning che possiamo fornire sono relativi ad errori nella [formattazione del documento](https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/index/scrivere-un-documento.html).
- rispetto al tema del burocratese ti consiglio anche:
  - [Linee guida di design per i servizi web della Pubblica Amministrazione - Linguaggio](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/bozza/doc/content-design/linguaggio.html)
  - [Le parole sono importanti](https://medium.com/designers-italia/le-parole-sono-importanti-4e2cdbf35ede)
  - [Design dell’informazione: lavori in corso](https://medium.com/designers-italia/design-dellinformazione-lavori-in-corso-7bc72ec7a8ea)

Se lo ritieni utile, su questo tema puoi anche aprire una discussione su [Forum Italia](https://forum.italia.it).

Grazie per il contributo!

**Comment by bfabio** [comment]
Corretto con #30
