### ISSUE TITLE
Iniziali Corte dei conti

### ISSUE THREAD

**Issue by altroisi** [italia/writing-toolkit#22]
Alla voce Corte del glossario si legge che le iniziali della Corte dei Conti sono entrambe maiuscole, rappresentando un'eccezione alla regola. Tuttavia, la maggior parte delle occorrenze sul [sito istituzionale](https://www.corteconti.it/), il simbolo e il logo ufficiali usano la notazione **Corte dei conti**, con la seconda c in minuscolo. Questa è anche la dicitura impiegata nelle norme, tra cui l'art.100 della Costituzione. A cosa è dovuta l'eccezione?

**Comment by bfabio** [comment]
@altroisi direi che è un errore :+1:  ho fatto una PR con la correzione.

**Comment by bfabio** [comment]
@altroisi riapro l'issue, sarà chiusa automaticamente quando la correzione sarà integrata
